# Generated by Django 6.0.4 on 2026-04-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_banksync_config_updated_at_alter_debt_member_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='bedroom_price_ur',
        ),
        migrations.RemoveField(
            model_name='historicalconfig',
            name='bedroom_price_ur',
        ),
        migrations.AddField(
            model_name='config',
            name='bedroom_price_ur_2',
            field=models.DecimalField(decimal_places=2, default=2.96, max_digits=10, verbose_name='Precio 2 dormitorios (UR)'),
        ),
        migrations.AddField(
            model_name='config',
            name='bedroom_price_ur_3',
            field=models.DecimalField(decimal_places=2, default=2.96, max_digits=10, verbose_name='Precio 3 dormitorios (UR)'),
        ),
        migrations.AddField(
            model_name='config',
            name='bedroom_price_ur_4',
            field=models.DecimalField(decimal_places=2, default=2.96, max_digits=10, verbose_name='Precio 4 dormitorios (UR)'),
        ),
        migrations.AddField(
            model_name='historicalconfig',
            name='bedroom_price_ur_2',
            field=models.DecimalField(decimal_places=2, default=2.96, max_digits=10, verbose_name='Precio 2 dormitorios (UR)'),
        ),
        migrations.AddField(
            model_name='historicalconfig',
            name='bedroom_price_ur_3',
            field=models.DecimalField(decimal_places=2, default=2.96, max_digits=10, verbose_name='Precio 3 dormitorios (UR)'),
        ),
        migrations.AddField(
            model_name='historicalconfig',
            name='bedroom_price_ur_4',
            field=models.DecimalField(decimal_places=2, default=2.96, max_digits=10, verbose_name='Precio 4 dormitorios (UR)'),
        ),
    ]
